# Generated by Django 3.0.5 on 2020-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('isFinish', models.BooleanField()),
                ('isAdult', models.BooleanField()),
                ('isFree', models.BooleanField()),
                ('theme', models.CharField(max_length=200, null=True)),
                ('platform', models.CharField(choices=[('N', 'Naver'), ('D', 'Daum'), ('L', 'Lezhin')], max_length=1)),
                ('thumbnail', models.URLField(max_length=300)),
            ],
            options={
                'ordering': ['genre', 'title'],
            },
        ),
    ]
