# Generated by Django 3.0.5 on 2020-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webtoon',
            options={'ordering': ['genre']},
        ),
        migrations.RemoveField(
            model_name='webtoon',
            name='author',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('webtoons', models.ManyToManyField(to='webtoon.Webtoon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
