# Generated by Django 3.0.5 on 2020-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20200508_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webtoon',
            options={},
        ),
        migrations.RenameField(
            model_name='webtoon',
            old_name='isAdult',
            new_name='is_adult',
        ),
        migrations.RenameField(
            model_name='webtoon',
            old_name='isFinish',
            new_name='is_finish',
        ),
        migrations.RenameField(
            model_name='webtoon',
            old_name='isFree',
            new_name='is_free',
        ),
        migrations.RemoveField(
            model_name='author',
            name='webtoons',
        ),
        migrations.AddField(
            model_name='webtoon',
            name='author',
            field=models.ManyToManyField(to='webtoon.Author'),
        ),
        migrations.RemoveField(
            model_name='webtoon',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='webtoon',
            name='theme',
        ),
        migrations.AddField(
            model_name='webtoon',
            name='genre',
            field=models.ManyToManyField(to='webtoon.Genre'),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='theme',
            field=models.ManyToManyField(null=True, to='webtoon.Theme'),
        ),
    ]
