# Generated by Django 3.0.5 on 2020-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0003_auto_20200512_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='webtoons', to='webtoon.Theme'),
        ),
    ]
