# Generated by Django 3.0.5 on 2020-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0004_auto_20200512_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='author',
            field=models.ManyToManyField(related_name='webtoons', to='webtoon.Author'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='genre',
            field=models.ManyToManyField(related_name='webtoons', to='webtoon.Genre'),
        ),
    ]
