# Generated by Django 3.0.5 on 2020-05-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0005_auto_20200514_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtoon',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='webtoon',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='webtoon',
            old_name='theme',
            new_name='themes',
        ),
    ]
