# Generated by Django 3.0.5 on 2020-05-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0007_auto_20200518_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtoon',
            old_name='is_free',
            new_name='is_pay',
        ),
    ]
