# Generated by Django 3.0.5 on 2020-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0008_auto_20200520_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='description',
            field=models.TextField(default='description for webtoon'),
        ),
    ]
