# Generated by Django 3.0.5 on 2020-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0009_webtoon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(default='description for theme'),
        ),
    ]
